import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/shared/layout/Layout";
import Header from "@/components/shared/layout/Header";
import Footer from "@/components/shared/layout/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-gray-100 text-gray-900"
      >
        <Header />
        <Layout>
          {children}
        </Layout>
        <Footer />
      </body>
    </html>
  );
}
